artifacts_root: artifacts


data_ingestion:
    root_dir: artifacts/data_ingestion
    source_URL: https://raw.githubusercontent.com/AhmAdO9/Machine_learning/master/chicken_disease/Chicken-fecal-images%20(8).zip
    local_data_file: artifacts/data_ingestion/data.zip
    unzip_dir: artifacts/data_ingestion 